Sprint 1/step 2
UvO1/react-burger pull request #1
Opened 2023-01-15 16:26 UTC by UvO1

2023-01-15 17:09 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать.
- Добавьте проверку успешности запроса.
- Допишите поля ингредиента.
- Добавьте isRequired там где его нет.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-15 17:09 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +	image: PropTypes.string.isRequired,
**Необходимо исправить**
Сейчас у вас несколько дубликатов этого кода. От него нужно избавиться. Чтобы это сделать создайте в отдельном файле константу с типизацией ингредиента и импортируйте всюду куда нужно. Так же тут не хватает некоторых полей ингредиента получаемого с сервера, их необходимо добавить.

2023-01-15 17:09 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +		console.log(isOpen);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией.

2023-01-15 17:09 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.js
> +function IngredientDetails(props){
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-01-15 17:09 UTC, andryxxa93 commented on src/components/modal/modal.js
> +	const handleCloseModalKey = event => {
**Можно лучше**
Можно сделать так как вы сделали. А можно подписываться на слушатель события `keydown` и вызывать функцию `onClosed` если было нажато `ESC`. Тогда не придется вызывать `focus` для модалки.

2023-01-15 17:09 UTC, andryxxa93 commented on src/components/app/App.tsx
> +		const ulrData = 'https://norma.nomoreparties.space/api/ingredients';
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-01-15 17:09 UTC, andryxxa93 commented on src/components/modal/modal.js
> +	onClick: PropTypes.object,
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2023-01-16 10:14 UTC, UvO1 commented
Добрый день! Спасибо большое за подробные комментарии.
Уточните, пожалуйста, на какие именно проблемы масштабирования стоит обратить внимание? Я растягивала компоненты бургер-конструктора вручную, тк подумала, что они не должны ограничиваться max-width.  Если это было ошибкой, я уберу эти изменения. 
Впервые пользуюсь гитхабом, возможно не очень понимаю как правильнее тут коммуницировать, прошу прощения.  Новую ссылку (на обновленный pull request) отправила через Яндекс Практикум.

2023-01-16 10:56 UTC, andryxxa93 commented
> Добрый день! Спасибо большое за подробные комментарии. Уточните, пожалуйста, на какие именно проблемы масштабирования стоит обратить внимание? Я растягивала компоненты бургер-конструктора вручную, тк подумала, что они не должны ограничиваться max-width. Если это было ошибкой, я уберу эти изменения. Впервые пользуюсь гитхабом, возможно не очень понимаю как правильнее тут коммуницировать, прошу прощения. Новую ссылку (на обновленный pull request) отправила через Яндекс Практикум.

У вас получается так - ширина картинок ингредиентов зависит от ширины секции с ингредиентами - чем она шире, тем шире становятся картинки ингредиентов. Вам стоит зафиксировать ширину секции с ингредиентами.

2023-01-16 11:04 UTC, andryxxa93 requested changes
Отлично, большая часть замечаний исправлена. Осталось только два поправить и работа будет принята.

 - Не во всех местах добавили `isRequired`
 - Поправьте ширину ингредиентов
 
Рекомендация:
- Попробуйте использовать в разработке пакет `pretier` - он поможет следовать единому общепринятому стилю оформления кода. Сейчас в некоторых местах есть проблема с табуляцией.

2023-01-16 11:04 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.js
> +    ingredient: messagePropTypes
**Необходимо исправить**
В этом и подобных местах не хватает `isRequired`

2023-01-16 13:15 UTC, UvO1 commented
Спасибо за пояснения, исправила.  Сделала максимальную ширину всего контента 1480 px, заодно чтобы и header не расползался совсем по углам экрана.

2023-01-16 19:36 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-22 16:59 UTC, merged